export enum Topic {
    NewPost = "NEW_POST",
    NewRoom = "NEW_ROOM",
    GET_ROOM_MESSAGES = "GET_ROOM_MESSAGES",
    LOGGED_IN = "LOGGED_IN",
    MAKE_FRIEND = "MAKE_FRIEND",
    DELETE_FRIEND = "DELETE_FRIEND",
    LOGGED_OFF = "LOGGED_OFF",
}
